### ISSUE TITLE
'Flurl.Http' already has a dependency defined for 'Newtonsoft.Json'.

### ISSUE THREAD

**Issue by rameshbabu745** [ringcentral/ringcentral-csharp-client#10]
If I am trying to install Ringcentral Client I got Below Error ,

Attempting to resolve dependency 'Flurl (≥ 2.2.1)'.
Attempting to resolve dependency 'Flurl.Http (≥ 1.1.1)'.
'Flurl.Http' already has a dependency defined for 'Newtonsoft.Json'.

I am Using Visual Studio 2010.

Kindly help asap. Thanks in Advance

**Comment by tylerlong** [comment]
Please upgrade NuGet.

And by they way I think it's a warning/information. You should be good to go ahead to try the library.

**Comment by rameshbabu745** [comment]
I already uninstalled and Reinstalled NuGet.

This is not a warning, it's an Error Message. Because Finally, it shows "Operation Failed"

**Comment by rameshbabu745** [comment]
It supports only higher versions of vs2010. Thanks

**Comment by tylerlong** [comment]
VS2010 only support NuGet 2.8: http://stackoverflow.com/questions/41557625/vs2010-and-nuget-why-v2-8-how-to-get-3-5

We have no plan to support NuGet 2.x. Please consider upgrading Visual Studio.
