### ISSUE TITLE
RingOut won't work

### ISSUE THREAD

**Issue by rameshbabu745** [ringcentral/ringcentral-csharp-client#11]
Below is my code.

If I try RingOut, I got a error like `Request to https://platform.devtest.ringcentral.com/restapi/v1.0/account/~/extension/~/ringout failed with status code 400 (Bad Request).`

Whats wrong with my code. Kindly reply ASAP

```cs
private RestClient rc;
    string from_num_Call = "+18007924060";
    string leadnum = "+1416-721-5424";

    public void Page_Load(object sender, EventArgs e)
    {
        RegisterAsyncTask(new PageAsyncTask(LoadSomeData));
    }

    public async Task LoadSomeData()
    {
        try
        {
            rc = new RestClient("MY_APP_KEY", "MY_APP_SECRET", "https://platform.devtest.ringcentral.com");
            await rc.Authorize("MY_PHONENUMBER", "MY_EXTENSION", "MY_PASSWORD");

            var requestBody = new
            {
                from = new { phoneNumber = "+18007924060" },
                to = new object[] { new { phoneNumber = "+1416-721-5424" } }
            };

            var temp = await rc.Restapi().Account().Extension().Ringout().Post(requestBody);
        }
        catch (Exception ex)
        {
            Alert.ShowAlert(this, ex.Message);
        }
    }
```

**Comment by tylerlong** [comment]
Could you please add a break point to the catch statement and inspect the inner exception?

According to the doc https://developer.ringcentral.com/api-docs/latest/index.html#!#RefRingOutCall.html

`request.Body.to` is NOT an array.

**Comment by rameshbabu745** [comment]
Thanks. I got another issue on the call log. If I called after that I got id( like 910 or any) and status. but if I get call log by id, got and error. In your sample code, you are using some encrypted Id. where do find that?
My needed is call goes to people after that we need to know all status of that call. but how will we know, because output has different id's ?Below is my code.

public async Task LoadSomeData()
  {
  try
  {
  rc = new RestClient("JHHdZSAXR2iDDVpmGRqQyg", "mXcliuINR7mQiNxb349ryAZXeGlnN9QrqWfsBsybAWvg", false);
  await rc.Authorize("+15817004045", "101", "Ringout1");

  var requestBody = new
  {
  from = new { phoneNumber = "+18007924060" },
  to = new { phoneNumber = "+1416-721-5424" }
  };

  var temp = await rc.Restapi().Account().Extension().Ringout().Post(requestBody);
  Alert.ShowAlert(this, temp.id);

  var callLogs = await rc.Restapi().Account().Extension().CallLog("910").Get();

  }
  catch (Exception ex)
  {
  Alert.ShowAlert(this, ex.Message);
  }
  }

**Comment by tylerlong** [comment]
You need to search the call logs: https://developer.ringcentral.com/api-docs/latest/index.html#!#RefExtensionCallLog.html

**Comment by rameshbabu745** [comment]
I already read the docs. Where to find "Internal identifier of a cal log record" at the time of call triggering.

**Comment by tylerlong** [comment]
I don't think it is possible. Call log won't be available until the call is ended.

Or could you please elaborate what kind of data are you trying to get? If the ringout is initialized by you, you should already know the caller, callee, timestamp...etc.

**Comment by grokify** [comment]
As mentioned, the `call-log` endpoint will have calls shortly after they end. Before then, active calls can be retrieved in the `active-calls` endpoint.

More information is available in the:

* API docs: http://ringcentral-api-docs.readthedocs.io/en/latest/calllog_introduction/
* API FAQ: http://ringcentral-faq.readthedocs.io/en/latest/call_log/

**Comment by tylerlong** [comment]
Close it for now, feel free to reopen.
