### ISSUE TITLE
Add helper support for MMS

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp-client#12]
MMS is now supported in the API. This is similar to Fax support.

* https://developer.ringcentral.com/api-docs/latest/index.html#!#RefCreateSMSMessage

**Comment by tylerlong** [comment]
Is there any sample code in any programming language? I cannot make it work.

**Comment by grokify** [comment]
**(1) Example Code**

There is an example implementation in the community Ruby SDK:

* Docs: https://github.com/ringcentral-ruby/ringcentral-sdk-ruby#sms-and-mms-examples
* Code: https://github.com/ringcentral-ruby/ringcentral-sdk-ruby/blob/master/lib/ringcentral_sdk/rest/request/sms.rb

**(2) Testing**

You can test with a standard mobile device that is text capable. If you do not have a device, we can use my number.

**(3) Release**

The API has been released and we should update the SDKs to include support. While the client apps will receive MMS and Group MMS support later, many customers use RingCentral to communicate with users that are not using RingCentral clients.

**Comment by tylerlong** [comment]
I do have a device. However, I don't think SMS/MMS could be sent to China numbers.
Let me have a try.

**Comment by tylerlong** [comment]
I forgot this issue.

I've got it done today.

RingCentral desktop app can view MMS.
