### ISSUE TITLE
subscription presence stopped working after couple of hours sometimes after couple of days, I still can make a call but no presence

### ISSUE THREAD

**Issue by hadimo** [ringcentral/ringcentral-csharp-client#15]
Hello,
I am working on the sdk for few months and I have the following issue:
subscription presence stopped working after couple of hours, sometimes after couple of days, I still can make a call but no presence.

I am using version 1.0.0 from github, also when I use latest ring central sdk from nuget nothing works.
I tried plenty of things and I found when I logged off and log back in after second attempts presence will stop also sometimes Subscription_ConnectEvent raise with very long delay and presence not working as well, is there any issue with pubnub.

when I close the program and run it again it works but it will stop after awhile.

Regards,
Hadi

**Comment by tylerlong** [comment]
A quick workaound is to `Renew` the subscription hourly: https://github.com/ringcentral/ringcentral-csharp-client/blob/master/RingCentral/SubscriptionService.cs#L108

By default it auto renews, but maybe there are network issues or other issues which prevents it to refresh successfully. So we Renew it manually every hour.

> I am using version 1.0.0 from github, also when I use latest ring central sdk from nuget nothing works.

Do you mean subscription or everything doesn't work?

**Comment by tylerlong** [comment]
Close because no more feedback.
