### ISSUE TITLE
novice question

### ISSUE THREAD

**Issue by krb-vci** [ringcentral/ringcentral-csharp-client#16]
I have never worked with your sdk before, and have some very basic questions.

Here's what i am trying to do:  I have a c# application that monitors certain business activities.  When certain conditions are met, or events occur, I want to initiate an outgoing phone call.  and have the user be able to talk to the person on the other end of the call.

The users are using Windows 7 and Windows 10 desktops, and will get a Ring Central Account (they don't have it yet).  (By the way, i have been a Ring Central customer for years - but only use the faxing feature).

So I see that i can install the Ring Central library, initiate an rc object, and do stuff like make calls.  How the the user actually talk?  Will the call automatically open on their Ring Central desktop app?  Or is there some other way?  Do i need to configure any resources so that they can use a headset on their computer - or is that done for them in the app settings?

Also - it there a minimum level of account that the user will need?

Thanks - I am trying to understand how this will look in action - which was not clear to me yet.

**Comment by tylerlong** [comment]
With this SDK, you can initiate a "ringout". Ringout is different from making a call directly and I am not sure if it's ideal for you.

The basic idea of ringout:
1. you make an api call and specify the from number and to number
2. an intermediate number will call the from number and to number
3. if both the from number and to number pick up the call, the intermediate number will connect them so they can talk.

If you want to make a direct call instead. I'd suggest the webrtc SDK:  https://github.com/ringcentral/ringcentral-web-phone

**Comment by krb-vci** [comment]
Hi Tyler,

Thanks for the reply.  I am not excited about the idea of using javascript, because this feature is a small part of a much larger project that is already written in c#.

The ringout idea may work – but I have a question.  When the intermediate number calls is there an announcement (I suspect there might be some kind of announcement like a google voice announcement – “will you accept a call from …” – or do the calls simply connect?  An announcement may get in the way of the process I need.  Is there a way I can test this process and see if it works for my client and this project?

Thanks,

Ken Blaker
