### ISSUE TITLE
Most Efficient Way to Download Call Recording Immediately After Call Completes

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp-client#18]
Good evening,

I saw the sample code on the readme of how to download Call Recordings, and I was wondering how to set up "watchers" on specific extensions and triggering the call download as soon as the call completes. 

Thank you as always!!!! 

This is the code I am referencing:

`var account = rc.Restapi().Account();

// List call Logs
var queryParams = new CallLogPath.ListParameters
{
    type = "Voice",
    view = "Detailed",
    dateFrom = DateTime.UtcNow.AddDays(-100).ToString("o"),
    withRecording = true,
    perPage = 10,
};
var callLogs = await account.CallLog().List(queryParams);

// download a call recording
var callLog = callLogs.records[0];
var content = await account.Recording(callLog.recording.id).Content().Get();
File.WriteAllBytes("test.wav", content.data);`

**Comment by tylerlong** [comment]
It is not a C# question. Please ask it here: https://devcommunity.ringcentral.com/
