### ISSUE TITLE
Web Based Project

### ISSUE THREAD

**Issue by heatharthur** [ringcentral/ringcentral-csharp-client#20]
I am having issue getting this to work on an MVC project. I used it on a winforms app with no difficulty. From what I can gather web based projects require oAuth 2.0 for authorization on the API. Does this client not instigate that? If not how can I go about making it work with oAuth 2.0?

**Comment by grokify** [comment]
This SDK does support OAuth 2.0. Here is an example app using the [Nancy .net framework](http://nancyfx.org/):

https://github.com/ringcentral/ringcentral-demos-oauth/tree/master/csharp-nancy
