### ISSUE TITLE
Problem while opening this project

### ISSUE THREAD

**Issue by Hussainiglobal** [ringcentral/ringcentral-csharp-client#23]
Hello,

I have download this for trail and after downloading successfully, i have tried to open RingCentral.sln but project didnt open properly. You can check in below image or attached image.

![12345678](https://user-images.githubusercontent.com/37141674/37087353-0d69e20c-2220-11e8-8711-b61055244ec0.JPG)

I want to add functionality to send and receive faxes in my ASP.Net MVC application. So do you have any sample project where i can test it.

Can you please guide....

**Comment by AndyHaas** [comment]
I have never download their test project I have always looked at the examples in GIT and copied what I needed in my own application. Also if we can keep 1 thread open it makes it a lot easier to help you out. #24

**Comment by tylerlong** [comment]
Hi, normally you don't need to download the source code of this project.

The recommended way to install this project is via NuGet. You install this project as a library to your own project just like you install any other libraries.

There are installation instructions on top of this page: https://www.nuget.org/packages/RingCentral.Client
