### ISSUE TITLE
Ring Central SDK or Client

### ISSUE THREAD

**Issue by Hussainiglobal** [ringcentral/ringcentral-csharp-client#24]
I want to create MVC web app to send and receive3 FAX so there are two option you have provided one is SDK and one ios Client. so which one i need to use? I wanrt to send fax from my mvc web applicationm so can you please guide which one i need to use

**Comment by AndyHaas** [comment]
You will use the SDK and follow the documentation. I was able to use this and send faxes easily with this 

https://github.com/ringcentral/ringcentral-csharp-client#send-fax

**Comment by tylerlong** [comment]
This(the current project we are viewing) is the right project: https://github.com/ringcentral/ringcentral-csharp-client

The SDK project has been deprecated.
