### ISSUE TITLE
API request throttling

### ISSUE THREAD

**Issue by xlorepdarkhelm** [ringcentral/ringcentral-csharp-client#25]
I am working on building a system that pulls the call logs using the csharp client, and we have an issue here where existing code for this same situation hits the limit of API calls available, and then breaks.

I have been trying to find a clever method of handling the API calls so I can make calls, but it will automatically restrict the number of calls actually performed to be within the limits RingCentral requires (like 10 per minute for Call Logs).

I was wondering if there is any plans on building that into the client code to limit the number of actual API calls automatically.

I have been looking at Reactive Extensions personally, but I am very new to C# so I have a lot of studying to do.

In theory, I would love to be able to.... maybe asynchronously call the API and have it automatically throttle the requests to RingCentral to the request limits we have available, and only make the request/return the result when the throttle allows for it.

Do you have any suggestions for how to accomplish this?

**Comment by tylerlong** [comment]
Currently this feature is not available in the C# client project.

But I know some community SDKs(not in C#) do have this feature. I will do more investigation and post back here.

**Comment by tylerlong** [comment]
If you want to do it yourself before we release an official version, please take advantages of the `Retry-After` header.

> Client may retry original request after getting this HTTP code not earlier than in a number of seconds returned in `Retry-After` header

**Comment by tylerlong** [comment]
Please refer to [rate limit handling best practices](https://github.com/ringcentral/ringcentral-api-docs/issues/30)

**Comment by xlorepdarkhelm** [comment]
Is there a way to get the headers from something like:

rc.Restapi().Account().CallLog()

?

**Comment by xlorepdarkhelm** [comment]
I figured out a solution that seems to work, going off of what the "rate limit handling best practices" link you gave explained.

Thanks.
