### ISSUE TITLE
Fix NuGet Project Site link

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp-client#26]
The "Project Site" link on the following NuGet page currently goes to the old URL which returns a 404 now.

NuGet page: https://www.nuget.org/packages/RingCentral.Client/

Please update to current site: https://github.com/ringcentral/ringcentral-csharp-client

**Comment by tylerlong** [comment]
Which version of ringcentral-csharp-client did you install? Could you please try latest version instead?

Can you reproduce the issue with an hello world style sample project?  I cannot reproduce it myself. The code seems fine. It might be an issue of how your IDE install and manage dependencies

**Comment by tylerlong** [comment]
fixed.
