### ISSUE TITLE
Could not load file or assembly 'PubNub-Messaging, Version=1.0.6201.20023

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp-client#27]
The following was posted on the RingCentral Dev Community:

https://devcommunity.ringcentral.com/ringcentraldev/topics/pubnub

---

I am integrating ring central c# package to asp.net mvc5 application.Autherization is done and when i try to call subscription it shows an error like 

> Could not load file or assembly 'PubNub-Messaging, Version=1.0.6201.20023, Culture=neutral, PublicKeyToken=dc66f52ce6619f44' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"PubNub-Messaging, Version=1.0.6201.20023, Culture=neutral, PublicKeyToken=dc66f52ce6619f44"

when i installed ring central client it added pubnub-messaging version 1.0.6151.29001, now i am unable to change the package.

This is my code,

```cs
var subscription = rc.Restapi().Subscription().New();

                subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/message-store");

                subscription.EventFilters.Add("/restapi/v1.0/account/~/extension/~/presence");

                subscription.ConnectEvent += (sender, args) =>
                {

                    Console.WriteLine("Connected:");

                    Console.WriteLine(args.Message);

                };

                subscription.NotificationEvent += (sender, args) =>
                {

                    Console.WriteLine("Notification:");

                    Console.WriteLine(args.notification);

                };

                subscription.ErrorEvent += (sender, args) =>
                {

                    Console.WriteLine("Error:");

                    Console.WriteLine(args.Message);

                };

                var sub = await subscription.Register();
```

**Comment by tylerlong** [comment]
Which version of ringcentral-csharp-client did you install? Could you please try latest version instead?

Can you reproduce the issue with an hello world style sample project?  I cannot reproduce it myself. The code seems fine. It might be an issue of how your IDE install and manage dependencies
