### ISSUE TITLE
Authorization issue in RestClient 

### ISSUE THREAD

**Issue by KundanJaiswal** [ringcentral/ringcentral-csharp-client#28]
Hi,
I have installed RingCentral.Client package to call ring out but when come to Authorization flow it gives an error at rc.Authorize(username,"",password);
Below I attached an image, please guide me to get success on it.
![capturesnipet](https://user-images.githubusercontent.com/38454637/38870948-fa552f74-426c-11e8-84f1-9181e52effb8.PNG)

**Comment by tylerlong** [comment]
Please reference: https://github.com/dotnet/standard/issues/542
