### ISSUE TITLE
Call-Forwarding returning null

### ISSUE THREAD

**Issue by Corey10e** [ringcentral/ringcentral-csharp-client#29]
When I am calling call-forwarding with an extensionId defined it comes back null on all values except URI.  When using the API Explorer I get values back.  (I have tried this same code with caller-id and it works fine).  Here is the code I am using:

    RestClient rc = new RestClient(_clientId, _clientSecret);
            await rc.Authorize(_username, _extension, _password);
            var rcClient = rc.Restapi().Account("~");

            List<CallFwdRecord> exts = new List<CallFwdRecord>();
            foreach (DataRow dr in dt.Rows)
            {
                var extn = await rcClient.Extension(dr["id"].ToString()).ForwardingNumber().Get();
    }

Note that when I use the API Explorer this is the URI it uses:
    https://platform.devtest.ringcentral.com/restapi/v1.0/account/~/extension/237848004/forwarding-number

However when using the charp-client this is the URI it uses:
  
  https://platform.devtest.ringcentral.com/restapi/v1.0/account/237848004/extension/237848004/forwarding-number?page=1&perPage=100

**Comment by tylerlong** [comment]
Please refer to: https://devcommunity.ringcentral.com/ringcentraldev/topics/forwardingnumber-always-come-back-as-null?utm_source=notification&utm_medium=email&utm_campaign=reply_like&utm_content=topic_link

If you want to get a list of forwarding numbers, use `List` instead of `Get`.
