### ISSUE TITLE
Authorize method prematurely ending unit test

### ISSUE THREAD

**Issue by rjgeorge** [ringcentral/ringcentral-csharp-client#30]
I am new to RC and trying to use the C# SDK.  Call to await rc.Authorize(RingCentralConfig.Instance.username, RingCentralConfig.Instance.extension, RingCentralConfig.Instance.password); is just ending execution  of my unit test.  The documentation is fairly weak on API response and exception handling.  However, since the debug session just ends I have nothing to work with.

**Comment by tylerlong** [comment]
What do you mean by "ending execution"? Are there any exceptions?

`await ... ` is async code and it won't block your app. So if there is no more code after that, the app simple quits (normally).

**Comment by rjgeorge** [comment]
No exceptions.  There is code after the await call but it was not hitting it. I added a blocking statement in the calling method and it hit the breakpoint so I got it working again.  This can be closed.  Thanks!

**Comment by AndyHaas** [comment]
@rjgeorge If you are doing a console app you need to make sure you keeps the console open somehow. I achieved this by doing a do while around the async function. This kept the console app running until I got a response from the API.

If you are doing a form then as long as the form stays open the async will run
