### ISSUE TITLE
Error on subscription registration

### ISSUE THREAD

**Issue by shridharjjoshi86** [ringcentral/ringcentral-csharp-client#33]
Hi,

I am getting error on authorization registration as 

> Method not found: 'System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage> Flurl.Http.GeneratedExtensions.PostUrlEncodedAsync(Flurl.Http.IFlurlRequest, System.Object, System.Threading.CancellationToken, System.Net.Http.HttpCompletionOption).

Any clue to resolve this?

**Comment by tylerlong** [comment]
No, I've never encountered this.  Here is the sample code for subscription (which passes unit testing): https://github.com/ringcentral/ringcentral-csharp-client/blob/master/RingCentral.Test/SubscripotionTest.cs

I think it might because you didn't install all the dependencies (for example, Flurl)

**Comment by tylerlong** [comment]
@shridharjjoshi86 for programming questions, it's better to post them to https://devcommunity.ringcentral.com/ or ask them directly here: https://glipped.herokuapp.com/

For your question, you can go to https://devcommunity.ringcentral.com/ and search for "Unauthorized for this grant type
