### ISSUE TITLE
How about a complete example in C#

### ISSUE THREAD

**Issue by GraniteStateCollege** [ringcentral/ringcentral-csharp-client#43]
I find the code fragments in these examples to not be that useful. Could you create a complete example C# application (console) for getting all call logs and displaying the results?

**Comment by AndyHaas** [comment]
@GraniteStateCollege I can give you some tips even though I don't display the data I do store it in my database. Once I make the GET call to get all voicemails `/restapi/v1.0/account/~/call-log?type=Voice&view=Detailed&withRecording=false`. I then go through the model and parse out the data and then push it into a data table.

What issue are you currently having or what are you trying to achieve?

**Comment by GraniteStateCollege** [comment]
Thanks for responding. The issue I am having is that I can't seem to get this to work at all. I have the code below that uses the client api but doesn't seem to get authorized as I can't get a response after calling rc..Authorize():
using RingCentral;
namespace ringCentralLogs
{
    class Program
    {
	static void Main(string[] args)
        {
            Conn();
        }

        static async void Conn()
        {
            RestClient rc = new RestClient("clientId", "ClientSecret");

            await rc.Authorize("username", "", "password");
            var extension = rc.Restapi().Account().Extension();
            var callLogs = extension.CallLog().List(new { direction = "Outbound" });
            Console.WriteLine(callLogs.Id);

            await rc.Revoke();
            return;
        }
    }
}

**Comment by AndyHaas** [comment]
@GraniteStateCollege did you get this resolved?

I don't use the fancy model so I would have to try to recreate using the fancy model and see what happens.
