### ISSUE TITLE
Create subscription after token refreshed

### ISSUE THREAD

**Issue by shridharjjoshi86** [ringcentral/ringcentral-csharp-client#46]
Hi,

I have set RC object to auto refresh the token, and subscribed to the detailedtelephony event to get incoming call notifcation. I have also subscribed to autorefresh event of RC object to get the refreshed token and assigned it  to global RC object.This works fine. I would like to know if the token gets refreshed after every hour or so, do we need to subscribe to the detailedtelephony  event again i.e. everytime token get refreshed?

**Comment by tylerlong** [comment]
If you want to know when token gets refreshed, take advantages of the `TokenRefreshed` event: https://github.com/ringcentral/ringcentral-csharp-client#events

Or you can disable auto refresh, do the refresh yourself. Then you have full control over token refreshing.

I don't think you need to subscribe to the `detailedtelephony` event again after token refreshed.
