### ISSUE TITLE
Add documentation for Auth Code

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-csharp-client#48]
Update README.md to include mention of and docs for OAuth Auth Code grant:

https://github.com/ringcentral/ringcentral-demos-oauth/tree/master/csharp-nancy

This can address questions like the following:

https://stackoverflow.com/questions/52449873/how-to-use-sso-with-ringcentral-c-sharp-sdk

Ideally, this would include migrating the C# demo to RingCentral Tutorials like the following:

https://github.com/ringcentral-tutorials/oauth-js-demo

**Comment by tylerlong** [comment]
We do not maintain this SDK any more. Every user should use [RingCentral.NET](https://github.com/ringcentral/ringcentral.net)
