### ISSUE TITLE
Project ran fine for 290 minutes, then an exception was thrown (see included) 

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp-client#5]
Hi Tyler,

I had this project running for essentially 12 hours last night, with a few starts and stops.  Around 290 minutes in, the exception below occurred.  I'm still learning how to understand exception messages and I don't really know what to look for in order to find the cause based on this.  Do you have any idea what could have caused this?

Thanks!!

System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at FaxVMAPI.Program.Ext1(RestClient rc) in C:\Users\Administrator\Desktop\API\FaxVMAPI\FaxVMAPI\Program.cs:line 53
       at FaxVMAPI.Program.OnTimedEvent(Object source, ElapsedEventArgs e, RestClient rc) in C:\Users\Administrator\Desktop\API\FaxVMAPI\FaxVMAPI\Program.cs:line 158
       at FaxVMAPI.Program.<>c__DisplayClass0_0.<Main>b__0(Object sender, ElapsedEventArgs e) in C:\Users\Administrator\Desktop\API\FaxVMAPI\FaxVMAPI\Program.cs:line 24
       at System.Timers.Timer.MyTimerCallback(Object state)
  InnerException: 
       HResult=-2146233088
       Message=Request to https://platform.devtest.ringcentral.com/restapi/v1.0/account/~/extension/~/message-store/2644719004/content/2644719004 failed with status code 401 (Unauthorized).
       Source=Flurl.Http
       StackTrace:
            at Flurl.Http.Configuration.FlurlMessageHandler.<SendAsync>d__1.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\Configuration\FlurlMessageHandler.cs:line 59
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Flurl.Http.FlurlClient.<SendAsync>d__28.MoveNext() in C:\projects\flurl\src\Flurl.Http.Shared\FlurlClient.cs:line 201
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at RingCentral.RestClient.<GetBinary>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at RingCentral.RestClient.<Get>d__5`1.MoveNext()
       InnerException:

**Comment by tylerlong** [comment]
It seems that you didn't paste the full stack trace because the last line is:

> InnerException:

And for your app to go production, it's necessary to catch those exceptions. Because the system doesn't promise 100% up time and sometimes you will get 503 HTTP errors. It's a good practice to catch and handle such exceptions.

Of cause we need to take a look of the inner exception and figure out what's the root cause. It's helpful if you can provide me with more logs.

**Comment by jmol123** [comment]
Hi Tyler, 

Do you have any sample code that includes a way to catch a thrown exception?  How would be the best way to catch it and handle it?  Thanks!!

**Comment by tylerlong** [comment]
A quick and dirty solution could be like this:

```csharp
public MyBusinessLogic()
{
    // all the things you want to do with the API
}


...


while(true)
{
    try {
        MyBusinessLogic()
    } catch(catch (Exception e)) {
        Console.WriteLine(e.Message) // add a break point here to inspect the exception.
    }
}
```


Please note that code above is for development/debugging only. Use break point to inspect the exception and figure out the root cause of the exception.

**Comment by tylerlong** [comment]
Here is the code I wrote according to your requirements:

### Every 10 minutes download Fax and Voice Mail from all the extensions in the company.

```cshap
using RingCentral;
using System;
using System.IO;
using System.Threading;
using System.Timers;

namespace FaxDownloadingDemo
{
    class Program
    {
        private static string outputFolder = @"...";

        static void Main(string[] args)
        {
            var rc = new RestClient("...", "...", false);
            var temp = rc.Authorize("...", "...", "...").Result;
            Console.WriteLine("logged in");

            System.Timers.Timer timer = new System.Timers.Timer();
            timer.Elapsed += new ElapsedEventHandler((sender, e) => OnTimedEvent(rc));
            timer.Interval = 600000; // Set the Interval to 10 minutes.
            timer.Start();
            OnTimedEvent(rc);

            Console.WriteLine("Press \'q\' to quit the sample.");
            while (Console.Read() != 'q')
            {
                // do nothing
            }
            timer.Stop();
        }

        private static void OnTimedEvent(RestClient rc)
        {
            Console.WriteLine("Download started");
            try
            {
                Console.WriteLine("Downloading Fax");
                Download(rc, "Fax", "pdf");

                Console.WriteLine("Downloading VoiceMail");
                Download(rc, "VoiceMail", "wav");
            }
            catch (Exception e)
            {
                var exception = e;
                do
                {
                    Console.WriteLine("====================");
                    Console.WriteLine(exception.Message);
                    Console.WriteLine(exception.StackTrace);
                    Console.WriteLine("====================");
                    exception = exception.InnerException;
                } while (exception != null);
            }

            Console.WriteLine("Download finished");
        }

        private static string FormatDateTime(string str)
        {
            var datetime = DateTime.Parse(str);
            var datetimeString = datetime.ToString("MM-dd-yyyy_hh-mm-sstt");
            return datetimeString;
        }

        static void Download(RestClient rc, string messageType, string fileExtension)
        {
            var records = rc.Restapi().Account().Extension().List(new { perPage = 1000 }).Result.records;

            foreach (var item in records)
            {
                var extension = rc.Restapi().Account().Extension(item.id);
                var dateFrom = DateTime.UtcNow.AddMinutes(-10).ToString("o");
                var messages = extension.MessageStore().List(new { messageType = messageType, perPage = 1000, dateFrom = dateFrom, direction = "Inbound" }).Result.records;
                Console.WriteLine(string.Format("{0} {1} messages were found on the server for extension {2}", messages.Length, messageType, item.id));

                foreach (var message in messages)
                {
                    if (message.attachments != null && message.attachments.Length > 0)
                    {
                        var binary = extension.MessageStore(message.id).Content(message.attachments[0].id).Get().Result;
                        Thread.Sleep(10000); // sleep 10 seconds. Fetch too fast would trigger 429 rate limite exceeded error.
                        var datetime = FormatDateTime(message.creationTime);
                        var from = message.from.phoneNumber;
                        if (from.StartsWith("+"))
                        {
                            from = from.Substring(1);
                        }
                        File.WriteAllBytes(string.Format(@"{0}\{1}_From-{2}_id-{3}.{4}", outputFolder, datetime, from, message.id, fileExtension), binary.data);
                    }
                }
            }
        }
    }
}
```

To be frank it's almost all about C#, the RingCentral part is pretty simple.
