### ISSUE TITLE
Signed/StrongNamed version?

### ISSUE THREAD

**Issue by vsederburg** [ringcentral/ringcentral-csharp-client#51]
Have you given any thought to publishing a version signed with a strong named key?  I know there is a flurl and flurl.http available via nuget that are signed that could be used with it. Sorry if this has been asked before. I couldn't find anything about it.

Thanks!

**Comment by tylerlong** [comment]
We do not maintain this SDK any more. Every user should use [RingCentral.NET](https://github.com/ringcentral/ringcentral.net)
