### ISSUE TITLE
Not able to generate access tokens after Authorization

### ISSUE THREAD

**Issue by aohal-cemtrexlabs** [ringcentral/ringcentral-csharp-client#52]
Hi,

I have developed application using the GitHub library and using API version 0.34 and I am now making logging request in Sandbox environment and after clicking on Authorize button I am getting new blank screen and when in debugging mode I checked I am getting null tokens. Please can anybody help me on how to fix this issue?.

Regards

**Comment by tylerlong** [comment]
We do not maintain this SDK any more. Every user should use [RingCentral.NET](https://github.com/ringcentral/ringcentral.net)
