### ISSUE TITLE
App cleared for Production - Need to find specific extensions

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp-client#6]
I am trying to setup the code such that it monitors the extensions I need to monitor.  With this line of code, I only get 100 extensions.
`var extensions = rc.Restapi().Account().Extension().List().Result.records;`

How do I get the list of all extensions?  It also doesn't sort by Extension#.  Is there a way to sort these results by Extension#. I need to run this to find their IDs so I can run the code for every specific extension.

Thanks!!

**Comment by jmol123** [comment]
Nevermind!  I was able to figure this out.  The code below will pull the first 2500 extensions of the account (sorted by ext #) and output to a text file with Ext: # and ID: # so that a call can be made directly to one extension by using `var extension = rc.Restapi().Account().Extension("ID#)`


` var extensions = rc.Restapi().Account().Extension().List(new { perPage = 2500 }).Result.records;
            var count = 0;
            string path = @"PATH TO FILE";
            while (count < 2500)
            {
                foreach (var extension in extensions)
                {
                    //Console.WriteLine(count.ToString());
                    //Console.WriteLine(extension.extensionNumber);

                    if (count.ToString() == extension.extensionNumber)
                    {
                        string field = "Ext: " + extension.extensionNumber + " ID: " + extension.id;
                        Console.WriteLine(field);

                        
                        // This text is added only once to the file.
                        if (!File.Exists(path))
                        {
                            // Create a file to write to.
                            using (StreamWriter sw = File.CreateText(path))
                            {
                                sw.WriteLine("Hello");
                            }
                        }

                        // This text is always added, making the file longer over time
                        // if it is not deleted.
                        using (StreamWriter sw = File.AppendText(path))
                        {
                            sw.WriteLine(field);
                        }
                    }

                }
                count = count + 1;
            }`

**Comment by tylerlong** [comment]
Awesome!

Actually I am not sure whether you are able to fetch as many as 2500 records. Because some of RingCentral's API endpoints only allow 1000 as maximum perPage limit. You will be fine if your account has fewer than 1000 extensions. But if there are 1000+ extensions, you can do pagination like this:

```csharp
var extensions = rc.Restapi().Account().Extension().List(new { perPage = 1000, page = 2 }).Result.records;
```

Code above returns page 2 of the results.

**Comment by jmol123** [comment]
My company only has ~160 extensions but the numbers range from 2 to ~2000 so that is why I made the range so wide.  I actually also meant to put perPage = 1000 in the code I pasted above, but Copy/Pasted the wrong version of the code.  Whoops!!

**Comment by tylerlong** [comment]
If there are only ~160 extensions, pagination is not needed. As I said I think you can fetch as many as 1000 records with single request.  All seem fine to me now. 👍
