### ISSUE TITLE
SDK Question: Is there a way to find out the last time the token was refreshed?

### ISSUE THREAD

**Issue by jmol123** [ringcentral/ringcentral-csharp-client#8]
I remember reading that the token gets refreshed automatically.  Is there a function call or something I could do to get the date/time of the last token refresh?  Thanks!!

**Comment by tylerlong** [comment]
There are two ways:

## option 1

Disable automatic refresh:

```csharp
rc.AutoRefreshToken = false;
```

Create a timer to refresh it manually: `rc.Refresh();` The it's fully under your control. Every time you refresh it, you can save the date/time.


## Option 2

You can listen to the token refresh event:

```csharp
rc.TokenRefreshed += (object sender, TokenEventArgs e) =>
{
    // save the date/time
};
```

**Comment by jmol123** [comment]
Option 2 worked perfectly.  Thank you so much!!
