### ISSUE TITLE
issue in installing through nuget

### ISSUE THREAD

**Issue by AhmedMunnawar** [ringcentral/ringcentral-csharp-client#9]
hi,
i am trying to install ringcentral-csharp-client using nuget package manager. but it throw an error
error description below :

Install-Package : 'Flurl.Http' already has a dependency defined for 'Newtonsoft.Json'.
At line:1 char:16
+ Install-Package <<<<  RingCentral.Client
 
Please advice,
Any help would be appreciated!!

**Comment by tylerlong** [comment]
Could you please post a screenshot? I have never seen this before.

**Comment by jmol123** [comment]
When I got this error I solved it by completely removing Nuget from Visual Studio and adding it back.  It seemed to me like it was a Nuget issue and not an SDK issue.

**Comment by tylerlong** [comment]
I just created a new project and installed the library via NuGet successfully.

I will close this issue. If you still have issues installing it, please reopen this issue and post some screenshots.
